### ISSUE TITLE
Change the `info` field from type string to sub-object

### ISSUE THREAD

**Issue by andreas-kupries** [FicHub/fichub.net#5]
```
{
  [...]
  "info": "She Summons Sea Things by the Sea Shore by mp3_1415player\n(8059 words, 1 chapters, status: ongoing, Updated: 2017-02-22 - 4 years 2 months 11 days  ago)\n",
  [...]
}
```

The `info` field in the returned json contain a number of things I believe are of general interest to clients (title, author, words, chapters, status, last-update, since-last-update).
Having the information directly available as json fields (*) would be much nicer.
Right now the only way to get this data is to parse the string in some way.
While that is reasonably easy with the current format the format is not documented, i.e. may change in the future, and thus this is not a suitable long-term solution.

(*) While the ticket title alludes to these fields becoming sub fields of `info`, that is not the only way. Having them as new toplevel fields is certainly possible too.

**Comment by iridescent-beacon** [comment]
I've made a change to include most of what you mentioned in the `meta` field to match the existing error response format, and used this time to include the `slug`, `hashes`, and `urls` fields. The full response is a bit of a mess at the moment since the website needs proper api versioning support:

`https://fichub.net/api/v0/epub?q=https://www.fanfiction.net/s/7597067/1/Storybook-Hero`
```json
{
  "epub_url": "/cache/epub/tTyB8GfC/Storybook_Hero_by_dogbertcarroll-tTyB8GfC.epub?h=2fdd96b7c8f26a0a0b008b94aa1182ba",
  "err": 0,
  "fixits": [],
  "hashes": {
    "epub": "2fdd96b7c8f26a0a0b008b94aa1182ba"
  },
  "html_url": "/cache/html/tTyB8GfC?cv=26&eh=2fdd96b7c8f26a0a0b008b94aa1182ba",
  "info": "Storybook Hero by dogbertcarroll\n(20978 words, 8 chapters, status: ongoing, Updated: 2018-12-20 - 2 years 4 months 12 days  ago)\n",
  "meta": {
    "author": "dogbertcarroll",
    "chapters": 8,
    "created": "2011-11-30T21:23:09",
    "description": "<p>Harry is sure he's living in a fairy tale with himself as the hero. Really, what else makes sense?</p>",
    "extraMeta": "Rated: Fiction T - Language: English - Genre: Humor - Characters: Harry P. - Reviews: 1,437 - Favs: 4,075 - Follows: 4,526",
    "id": "tTyB8GfC",
    "source": "https://www.fanfiction.net/s/7597067/1/Storybook-Hero",
    "status": "ongoing",
    "title": "Storybook Hero",
    "updated": "2018-12-20T20:01:23",
    "words": 20978
  },
  "mobi_url": "/cache/mobi/tTyB8GfC?cv=26&eh=2fdd96b7c8f26a0a0b008b94aa1182ba",
  "pdf_url": "/cache/pdf/tTyB8GfC?cv=26&eh=2fdd96b7c8f26a0a0b008b94aa1182ba",
  "q": "https://www.fanfiction.net/s/7597067/1/Storybook-Hero",
  "slug": "Storybook_Hero_by_dogbertcarroll-tTyB8GfC",
  "urlId": "tTyB8GfC",
  "urls": {
    "epub": "/cache/epub/tTyB8GfC/Storybook_Hero_by_dogbertcarroll-tTyB8GfC.epub?h=2fdd96b7c8f26a0a0b008b94aa1182ba",
    "html": "/cache/html/tTyB8GfC?cv=26&eh=2fdd96b7c8f26a0a0b008b94aa1182ba",
    "mobi": "/cache/mobi/tTyB8GfC?cv=26&eh=2fdd96b7c8f26a0a0b008b94aa1182ba",
    "pdf": "/cache/pdf/tTyB8GfC?cv=26&eh=2fdd96b7c8f26a0a0b008b94aa1182ba"
  }
}
```

The `extraMeta` field is a string and currently is only ever non-`null` on FFN works -- there's a few TODO items about parsing it into a real object that varies from source to source and adding it for other sources.

The relative date information is not included since the code generating it is a holdover and probably needs replaced entirely.

Ultimately, this endpoint was meant for use by fichub.net to use in the UI of epub generation and not really public consumption. I'm working towards providing better machine usable/stable endpoints that are specific to just metadata (which might simply being finally opening up the underlying api [Alexandria](https://fanfic.dev/)). In the mean time, if there's anything else you'd like to see changed about the current endpoint, or if you're interested in anything else please let me know! :)

**Comment by andreas-kupries** [comment]
Thank you for the quick work. That works quite nicely in my script.
It is a bit like the fichub cli (*), except it stores information in an sqlite database.
Not the epubs, just the meta data.

(*) Pretty sure that fh cli did not exist when I wrote it ... Yep, cli looks to be about 2 weeks old, and my script is older, although only slightly.
