### ISSUE TITLE
requirements.txt?

### ISSUE THREAD

**Issue by mid-kid** [FicHub/fichub.net#9]
A simple list of libraries required to run this site would be nice. I'm unsure where to get "oil" and "authentications".

**Comment by iridescent-beacon** [comment]
Sorry for the late reply; been very busy. Should be able to push a change to address this issue this weekend, but until then:
* oil is https://github.com/FanFicDev/python-oil and probably needs removed
* authentications.py is based on [authentications.ex.py](https://github.com/FicHub/fichub.net/blob/master/authentications.ex.py)

Beyond the actual code dependencies I need to setup a dummy/test api server for people that want to play around. Theoretically you can run Alexandria from https://github.com/FanFicDev/hermes yourself, but it's a lot of setup right now. Working on getting a basic Dockerfile put together in https://github.com/FicHub/infra-dev .

I'll do my best to answer any questions you have until that's all setup and documented better, so feel free to ask :)

**Comment by iridescent-beacon** [comment]
Well that took a bit longer than I anticipated :)  `requirements.txt` now exists, and the `README` has been expanded to be clearer about dependencies. [infra-dev](https://github.com/FicHub/infra-dev) actually runs everything you need on the FicHub side, but Alexandria is still pending. Going to close this issue since the original issue is resolved, and more work will be done in other repos.
